stages:
  - build
  - publish

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  DIST_DIR: "$CI_PROJECT_DIR/dist"
  PACKAGE_NAME: "${CI_PROJECT_NAME}"

default:
  tags:
    - build
    - common
    - lnsk

cache:
  paths:
    - .cache/pip

before_script:
  - pip install --upgrade pip setuptools wheel
  - pip install poetry

build:
  stage: build
  script:
    - poetry install --without dev
    - poetry build
  artifacts:
    paths:
      - dist/*.whl
      - dist/*.tar.gz

publish:
  stage: publish
  dependencies:
    - build
  script:
    - poetry config repositories.gitlab "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi"
    - poetry config http-basic.gitlab gitlab-ci-token "${CI_JOB_TOKEN}"
    - poetry publish --repository gitlab
  only:
    - main
    - tags